# Generated by Django 4.1.1 on 2022-09-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='lembrarsenha',
            field=models.BooleanField(default=False),
        ),
    ]
